//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blackjack
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dealer_DB
    {
        public Dealer_DB()
        {
            this.Dealer_Hand_DB = new HashSet<Dealer_Hand_DB>();
        }
    
        public int Id { get; set; }
        public int save_id { get; set; }
        public int hand_value { get; set; }
        public double x_offset { get; set; }
    
        public virtual Saves_DB Saves_DB { get; set; }
        public virtual ICollection<Dealer_Hand_DB> Dealer_Hand_DB { get; set; }
    }
}
